# Generated by Django 4.2.19 on 2025-02-24 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, verbose_name='Наименование продукта')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('customer_email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта')),
                ('status', models.CharField(choices=[('created', 'created'), ('processing', 'created'), ('completed', 'created'), ('cancelled', 'created')], default='created', max_length=10, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказ',
            },
        ),
    ]
