# Generated by Django 4.2.19 on 2025-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='created', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
