# Generated by Django 4.2.19 on 2025-02-24 13:43

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[orders.models.validate_quantity_zero], verbose_name='Количество'),
        ),
    ]
